/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:888c8298-3fa2-4f9d-b8c3-559bd024ba36",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PBtMHkUnP",
    "aws_user_pools_web_client_id": "4ap7m61vkjgkd3a5jmfgf03iec",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://cn3vknaimbdfhi5xrn3rf26olq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-agnpm67tyzf4fekqjfij2bhoh4",
    "aws_user_files_s3_bucket": "zone-todo-storage-dc13f9c2104712-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
